apiVersion: v1
kind: Service
metadata:
  namespace: marknotes
  name: node-page-service
spec:
  type: NodePort
  selector:
    app: marknotes-pod
  ports:
    - protocol: TCP
      port: 30100
      targetPort: 30100
      nodePort: 30100
      name: "app-access"
    # - protocol: TCP
    #   port: 3001
    #   targetPort: 3001
    #   nodePort: 30101
    #   name: "build-access"
    - protocol: TCP
      port: 27017
      targetPort: 27017
      nodePort: 30121
      name: "db-access"
    - protocol: TCP
      port: 5000
      targetPort: 5000
      nodePort: 30110
      name: "api-access"