apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  namespace: marknotes
  name: app-pvc
spec:
  storageClassName: manual
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 5Gi
  volumeName: "marknotes-pv"