apiVersion: v1
kind: PersistentVolume
metadata:
  namespace: marknotes
  name: mongodb-pv
  labels:
    type: local
spec:
  storageClassName: manual
  capacity:
    storage: 5Gi
  accessModes:
    - ReadWriteOnce
      # persistentVolumeReclaimPolicy: Retain
  hostPath:
    path: "/srv/pv/MarkNotes/db"
